import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface PDFReportOptions {
  title: string;
  data: Array<{ label: string; value: string | number }>;
  fileName: string;
}

export function generatePDFReport(options: PDFReportOptions) {
  const doc = new jsPDF();
  
  // Header section
  doc.setFillColor(30, 58, 138); // #1e3a8a
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("SalaryCalculator.my", 14, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Accurate Malaysian HR Calculators", 14, 32);

  // Title section
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(options.title, 14, 55);

  const dateStr = new Date().toLocaleDateString('en-MY', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on: ${dateStr}`, 14, 62);

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 68, 196, 68);

  // Content Table
  autoTable(doc, {
    startY: 75,
    body: options.data.map(item => [item.label, item.value]),
    theme: 'plain',
    styles: {
      fontSize: 12,
      cellPadding: 6,
    },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [51, 65, 85], cellWidth: 100 },
      1: { fontStyle: 'normal', textColor: [15, 23, 42], halign: 'right' }
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    }
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(226, 232, 240);
  doc.line(14, pageHeight - 20, 196, pageHeight - 20);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by salarycalculator.my", 14, pageHeight - 12);
  doc.text("Disclaimer: This report is generated for descriptive purposes.", 14, pageHeight - 7);

  // Trigger automatic download
  doc.save(`${options.fileName}.pdf`);

  try {
    if (typeof (window as any).gtag === 'function') {
        (window as any).gtag('event', 'pdf_download_success', {
           event_category: 'calculator',
           report_name: options.fileName,
           method: 'auto_download'
        });
    }
  } catch(e) {}
}

